version: "3.8"

services:
  postgres-db:
    image: "postgres:14"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  pgadmin-view:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
  nestjs-backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres-db
    env_file:
      - ./.env

volumes:
  pgdata: